version: "3"
services:
  api:
    build: .
    depends_on:
      - postgres
    ports: 
      - 8000:8000
    environment:
      - PORT=8000
      - DATABASE_HOSTNAME=
      - DATABASE_PORT=
      - DATABASE_PASSWORD=
      - DATABASE_NAME=
      - DATABASE_USERNAME=
      - SECRET_KEY=
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=
    volumes:
      - ./postgres-db:/var/lib/postgresql/data